mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('allauth.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('organizer/', include('organizer.urls')),
]

organizer/urls.py
from django.urls import path
from . import views

app_name = 'organizer'
urlpatterns = [
    path('home', views.homepage, name='index'),
    path('assignments', views.ClassView.as_view(), name='assignments'),
    path('addclass', views.add_class, name='addclass'),
    path('addnote', views.add_note, name='addnote'),
    path('addassignment', views.add_assignment, name='addassignment'),
]

organizer/models.py
from django.db import models
from django.forms import ModelForm
from django.utils import timezone

# Class
class Class(models.Model):
    course_abbr = models.CharField(max_length=100, default='')
    course_num = models.CharField(max_length=100, default='')


class ClassForm(ModelForm):
    class Meta:
        model = Class
        fields = ['course_abbr', 'course_num']

# Assignment
class Assignment(models.Model):
    name = models.CharField(max_length=500, default='')
    due_date = models.DateField(default='')
    description = models.CharField(max_length=500, default='')
    for_class = models.CharField(max_length=100, default='')
    # make actual checkbox in html?
    checkbox = models.BooleanField(default=False)
    # change actual color in html?
    colorcode = models.CharField(max_length=500, default='')

    def __str__(self):
        return self.name + " due on " + str(self.due_date) + "for" + str(self.for_class)


class AssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        fields = ['name', 'due_date', 'description', 'checkbox', 'colorcode', 'for_class']

# Note
class Note(models.Model):
    note_name = models.CharField(max_length=100, default='')
    for_class = models.CharField(max_length=100, default='')
 

class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ['note_name', 'for_class']

organizer/forms.py
from django import forms
from .models import Class, Note, Assignment

class ClassForm(forms.Form):
    course_abbr = forms.CharField(label='Course Abbreviation', max_length=100)
    course_num = forms.CharField(label='Course Number', max_length=100)

class NoteForm(forms.Form):
    note_name = forms.CharField(label='Note name', max_length=100)
    for_class = forms.CharField(label='Course Abbreviation', max_length=100)

class AssignmentForm(forms.Form):
    name = forms.CharField(max_length=500)
    due_date = forms.DateField()
    description = forms.CharField(max_length=500)
    for_class = forms.CharField(label='Course Abbreviation', max_length=100)
    # make actual checkbox in html?
    checkbox = forms.BooleanField()
    # change actual color in html?
    colorcode = forms.CharField(max_length=500)

organizer/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.views.generic.list import ListView
from .models import Assignment, Class, Note
from .forms import ClassForm, NoteForm, AssignmentForm

# Homepage
def homepage(request):
    return render(request, 'organizer/generic_template.html')

# add a class
def add_class(request):
    if request.method == 'POST':
        form = ClassForm(request.POST)
        if form.is_valid():
            c = Class()
            c.course_abbr = form.cleaned_data['course_abbr']
            c.course_num = form.cleaned_data['course_num']
            c.save()
            return HttpResponseRedirect(reverse('organizer:assignments'))
        else:
            return HttpResponseRedirect(reverse('organizer:addclass'))
    form = ClassForm()
    return render(request, 'organizer/addclass.html', {'form': form})

# add a note file
def add_note(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            n = Note()
            n.note_name = form.cleaned_data['note_name']
            n.for_class = form.cleaned_data['for_class']
            n.save()
            return HttpResponseRedirect(reverse('organizer:assignments'))
        else:
            return HttpResponseRedirect(reverse('organizer:addnote'))
    form = NoteForm()
    return render(request, 'organizer/addnote.html', {'form': form})

# add an assignment file
def add_assignment(request):
    if request.method == 'POST':
        form = AssignmentForm(request.POST)
        if form.is_valid():
            a = Assignment()
            a.name = form.cleaned_data['name']
            a.due_date = form.cleaned_data['due_date']
            a.description = form.cleaned_data['description']
            a.for_class = form.cleaned_data['for_class']
            a.checkbox = form.cleaned_data['checkbox']
            a.colorcode = form.cleaned_data['colorcode']
            a.save()
            return HttpResponseRedirect(reverse('organizer:assignments'))
        else:
            return HttpResponseRedirect(reverse('organizer:addassignment'))
    form = AssignmentForm()
    return render(request, 'organizer/addassignment.html', {'form': form})


# view for assignments/notes page
class ClassView(generic.ListView):
    model = Class
    template_name = 'organizer/assignments.html'
    context_object_name = 'latest_class_list'
    qs = Class.objects.all()
    def get_context_data(self, **kwargs):
        context = super(ClassView, self).get_context_data(**kwargs)
        context['notes'] = Note.objects.all()
        context['assignments'] = Assignment.objects.all()
        return context

organizer/templates/organizer/addassignment.html
{% extends 'organizer/generic_template.html' %}
{% load bootstrap5 %}
{% load static %}

{% block content %}
<form action = "{% url 'organizer:addassignment' %}" method = "post" style="width: 75%; text-align: center">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <div><input type="submit" value="Submit"></div>
    {% endbuttons %}
</form>
{% endblock %}

organizer/templates/organizer/addclass.html
{% extends 'organizer/generic_template.html' %}
{% load bootstrap5 %}
{% load static %}

{% block content %}
<form action = "{% url 'organizer:addclass' %}" method = "post" style="width: 75%; text-align: center">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <div><input type="submit" value="Submit"></div>
    {% endbuttons %}
</form>
{% endblock %}

organizer/templates/organizer/addnote.html
{% extends 'organizer/generic_template.html' %}
{% load bootstrap5 %}
{% load static %}

{% block content %}
<form action = "{% url 'organizer:addnote' %}" method = "post" style="width: 75%; text-align: center">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <div><input type="submit" value="Submit"></div>
    {% endbuttons %}
</form>
{% endblock %}

organizer/templates/organizer/assignments.html
{% extends 'organizer/generic_template.html' %}
{% load bootstrap5 %}
{% load static %}

{% block content %}
    {% if latest_class_list %}
    <ul>
        {% for c in latest_class_list %}
            <h3 style="text-align:center">{{ c.course_abbr }}</h3>
            <table class="table">
                <thead>
                    <tr style="text-align:center;">
                        <th scope="col">Notes</th>
                        <th scope="col">Assignments</th>
                    </tr>
                </thead>
                <tbody>
                    {% if notes %}
                        {% for n in notes %}
                            {% if n.for_class == c.course_abbr %}
                                <tr style="text-align:center;" >
                                    <td>{{n.note_name}}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    <!-- NEED TO FIX FORMAT OF TABLE!!!! -->
                    {% if assignments %}
                        {% for a in assignments %}
                            {% if a.for_class == c.course_abbr %}
                                <tr style="text-align:center;">
                                    <td>{{a.name}}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    <tr style="text-align:center;">
                        <td><a href ="{% url 'organizer:addnote' %}">
                            <button>Add notes</button>
                        </a></td>
                        <td><a href ="{% url 'organizer:addassignment' %}">
                            <button>Add assignments</button>
                        </a></td>
                    </tr>
                </tbody>
            </table>
        {% endfor %}
    </ul>
    {% else %}
        <p style="color:black;">No classes available.</p>
    {% endif %}

    <!-- change this -->
    <a href="{% url 'organizer:addclass' %}">Add class</a>


{% endblock %}

organizer/templates/organizer/generic_template.html
<html style="min-height:100%; position: relative;">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <title>Assignment Organizer</title>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark" style="padding-left:3%;padding-right:3%;">
        <h1 class="navbar-brand">Assignment Organizer</h1>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'organizer:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'organizer:assignments' %}">Notes/Assignments</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Calendar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log out</a>
                </li>
            </ul>
        </div>
    </nav>
    <body class="bg-light" style="margin-bottom:60px;" >
        {% block content %}
        {% endblock %}
    </body>
    <footer class="footer text-center text-light bg-dark fixed-bottom" style="height:60px;">
        <p>CS3240 | Group A-26 | Fall 2021<br>
            Matthew Ippolito, Justin Dubuque, Olivia Kaczmarskyj, Anh Nguyen, Stephen Boakye</p>
    </footer>
</html>

templates/index.html
{% load socialaccount %}
<!-- WE CAN CHANGE THIS PAGE OR THE FOLDER PATHS LATER -->
<html>
<body>
<h1>Google Login </h1>
{% if user.is_authenticated %}
  <p>Welcome, You are logged in as {{ user.username }}</p>
  <a href="{% url 'organizer:index' %}">Click here to proceed to the Assignment Organizer</a><br>
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <a href="{% provider_login_url 'google' %}">Login with Google</a>
{% endif %}
</body>
</html>